name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare HTML
        run: |
          # Create a temporary file with the new content
          awk '/<head>/{print;print "    <meta http-equiv=\"Content-Security-Policy\" content=\"default-src * '\''unsafe-inline'\''; connect-src https://api.github.com; script-src * '\''unsafe-inline'\''; style-src * '\''unsafe-inline'\'';\">"; print "    <script>window.config={apiKey:\"${{ secrets.API_KEY }}\",orgName:\"Krypto-Hashers-Community\"};console.log(\"Config loaded successfully\");</script>"; print "    <script src=\"js/api.js\"></script>"; print "    <script src=\"js/main.js\"></script>";next}1' index.html > temp.html
          
          # Replace the original file
          mv temp.html index.html
          
          # Verify the changes
          echo "Checking if scripts were injected:"
          grep -A 10 "<head>" index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 